services:
  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "10802:9000"
    command: [
      "vllm", "serve", "Qwen/Qwen3-0.6B",
      "--reasoning-parser", "deepseek_r1",
      "--served-model-name", "gemma3",
      "--host", "0.0.0.0",
      "--port", "9000",
      "--gpu-memory-utilization", "0.97",
      "--tensor-parallel-size", "1",
      "--max-model-len", "32768",
      "--disable-log-requests",
      "--dtype", "bfloat16",
      "--enable-chunked-prefill",
      "--enable-prefix-caching",
      "--max-num-batched-tokens", "32768",
      "--max-num-seqs", "512",
      "--chat-template-content-format", "openai",
    ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
